### ISSUE TITLE
How to set up and run

### ISSUE THREAD

**Issue by Steve9F** [bpmerkel/MIDIPianoJukebox#3]
I'm interested in trying this on my piano setup. Isn't clear to me from the readme and other content in the repository how to set this up.

**Comment by bpmerkel** [comment]
Hey Steve9F. The site is quite easy to setup. I build and publish the site using Visual Studio to a folder on a Windows laptop that acts as the "server". The site runs as server-side Blazor, and, aside from the playlist creation/management, is meant to "remotely control" a MIDI player that runs on the host server (which is connected via USB to the MIDI input ports on my player piano; I've also purchased a wireless Bluetooth MIDI connector, so the laptop-server doesn't have to be co-located with the piano). Copy over your folder of MIDI files to the server too.

Once you get the site running (I prefer to run the site under IIS for its resiliency capabilities), click over to Settings (button at top-right), and set the path to the root folder of your MIDI files. Then click Refresh to perform the import process--scanning all the MIDI files for metadata used for playlist creation, etc. The Refresh process creates a site LiteDB instance to persist all the data, your playlists, favorites, etc.

Also in Settings, choose the MIDI output device (which can be the 'Microsoft GS Wavetable Synth' device to synthesize the MIDI through the local speakers on the server.) When you have a MIDI link to your piano, the device should show up in the Settings device drop-down; and when you output to that, then the site will play selected MIDI playlist files to the piano.

You can then operate the site from your phone, iPad, etc... tracking your song rankings, skipping forward, etc. I've got playlists for "Ragtime", "Christmas", "Beatles", and plenty of other keywords. Fun!

**Comment by Steve9F** [comment]
Thank you, really appreciate the guidance. Will give it a go and let you know how it goes.

Steve
________________________________

**Comment by bpmerkel** [comment]
Checked-in new Setup section to README.md
